### PR TITLE
fix: simple-sort rule rename to imports and exports

### PR DESCRIPTION
**Pull request by linusklingzell**
eslint-plugin-simple-import-sort plugin has renamed `simple-import-sort/sort` since version 6. peerDependencies had version `>=4` which caused error of this rule if you install eslint-config-react in a new project

### CODE REVIEW

**Review by michaellopez — APPROVED** [review]

**Comment by michaellopez** [comment]
I have no idea why we use `>=`....it makes no sense to me. Its just asking for trouble (like this bug). I will make a new PR that changes `>=` to `^`.

**Comment by michaellopez** [comment]
On second thought, I'll let that thought sit for a while...need to reconsider this for all tooling repos.

I'll make sure to release this one though so you can work @linusklingzell

**Comment by michaellopez** [comment]
@linusklingzell available in [v0.14.0](https://github.com/weahead/eslint-config-react/releases/tag/v0.14.0)

**Comment by linusklingzell** [comment]
Yes I had also concerns about `>=`. I think it's the same problem with the husky tooling package. Got an error if I had husky: `6.0.0` but `4.5.0` version works. Have not debug that error more, don't work on windows 

Thanks @michaellopez 👍

**Comment by michaellopez** [comment]
@linusklingzell Yeh, Husky >4 seem to be a bit of a pain...I'm going over Husky >4 in another project, hopefully I can gain some insights there.

**Pull request merged**
